services:
  - type: web
    name: alcootrack
    env: php
    plan: free
    buildCommand: "composer install && npm install && npm run build"
    startCommand: "php artisan serve --host=0.0.0.0 --port=80"
    envVars:
      - key: APP_KEY
        value: "your-app-key"
    autoDeploy: true
